name: BIMCFD
channels:
    - defaults
    - conda-forge
    - oce
    - dlr-sc
    - ifcopenshell
dependencies:
    - python
    - pythonocc-core=7.4
    - occt=7.4
    - ifcopenshell
    - numpy
    - scipy
    - pandas
    - fuzzywuzzy
    - kivy
    # - kivymd # ver 0.104.2.dev0
    - rich
    - loguru
    - pyyaml
    - pyinstaller
    - tqdm
    - pytest
    - pylint
    - yapf
    - toml